In [ ]:
import pandas as pd
import numpy as np

In [ ]:
credits = pd.read_csv('/content/credits.csv')
credits.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [ ]:
meta = pd.read_csv('/content/movies_metadata.csv')

<ipython-input-3-5c3802c6ad91>:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  meta = pd.read_csv('/content/movies_metadata.csv')

In [ ]:
meta.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [ ]:
meta['release_date'] = pd.to_datetime(meta['release_date'], errors='coerce') #coerce will set any invalid value to NaN

In [ ]:
meta['year'] = meta['release_date'].dt.year

In [ ]:
meta.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,year
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,1995.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,1995.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,1995.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,1995.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,1995.0

In [ ]:
meta['year'].value_counts().sort_index()

year
1874.0       1
1878.0       1
1883.0       1
1887.0       1
1888.0       2
          ...
2015.0    1905
2016.0    1604
2017.0     532
2018.0       5
2020.0       1
Name: count, Length: 135, dtype: int64

In [ ]:
 #extracting 2017 data
 meta_2017 = meta.loc[meta.year == 2017,['genres','id','title','year']]

In [ ]:
meta_2017

,genres,id,title,year
26560,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",166426,Pirates of the Caribbean: Dead Men Tell No Tales,2017.0
26561,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",141052,Justice League,2017.0
26565,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",284053,Thor: Ragnarok,2017.0
26566,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",283995,Guardians of the Galaxy Vol. 2,2017.0
30536,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na...",245842,The King's Daughter,2017.0
...,...,...,...,...
45398,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",468707,Thick Lashes of Lauri Mäntyvaara,2017.0
45417,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",461297,Cop and a Half: New Recruit,2017.0
45437,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",455661,In a Heartbeat,2017.0
45453,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",404604,Mom,2017.0
45465,[],461257,Queerama,2017.0

In [ ]:
meta_2017.dtypes

genres     object
id         object
title      object
year      float64
dtype: object

In [ ]:
meta_2017['id'] = meta_2017['id'].astype(int)

In [ ]:
data = pd.merge(meta_2017, credits, on='id')

In [18]:
data

,genres,id,title,year,cast,crew
0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",166426,Pirates of the Caribbean: Dead Men Tell No Tales,2017.0,"[{'cast_id': 1, 'character': 'Captain Jack Spa...","[{'credit_id': '52fe4c9cc3a36847f8236a65', 'de..."
1,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",141052,Justice League,2017.0,"[{'cast_id': 2, 'character': 'Bruce Wayne / Ba...","[{'credit_id': '55ef66dbc3a3686f1700a52d', 'de..."
2,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",284053,Thor: Ragnarok,2017.0,"[{'cast_id': 0, 'character': 'Thor Odinson', '...","[{'credit_id': '56a93fa4c3a36872db001e7a', 'de..."
3,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",283995,Guardians of the Galaxy Vol. 2,2017.0,"[{'cast_id': 3, 'character': 'Peter Quill / St...","[{'credit_id': '59171547925141583c0315a6', 'de..."
4,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na...",245842,The King's Daughter,2017.0,"[{'cast_id': 0, 'character': 'King Louis XIV',...","[{'credit_id': '5431de49c3a36825d300007e', 'de..."
...,...,...,...,...,...,...
526,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",468707,Thick Lashes of Lauri Mäntyvaara,2017.0,"[{'cast_id': 0, 'character': 'Satu', 'credit_i...","[{'credit_id': '597e22f69251415d7801c74a', 'de..."
527,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",461297,Cop and a Half: New Recruit,2017.0,"[{'cast_id': 0, 'character': 'Detective Simmon...","[{'credit_id': '593ba0c29251410593009be3', 'de..."
528,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",455661,In a Heartbeat,2017.0,[],"[{'credit_id': '5981a15c92514151e0011b51', 'de..."
529,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",404604,Mom,2017.0,"[{'cast_id': 1, 'character': 'Devki Sabarwal',...","[{'credit_id': '58ee55bbc3a3683df500bd0f', 'de..."
530,[],461257,Queerama,2017.0,[],"[{'credit_id': '593e676c92514105b702e68e', 'de..."

In [19]:
#converting 'genre', 'cast', 'crew' columns to list
import ast
data['genres'] = data['genres'].map(lambda x: ast.literal_eval(x)) #the "literal_eval" helps to convert the string into a list
data['cast'] = data['cast'].map(lambda x: ast.literal_eval(x))
data['crew'] = data['crew'].map(lambda x: ast.literal_eval(x))

In [22]:
data.head()

,genres,id,title,year,cast,crew
0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",166426,Pirates of the Caribbean: Dead Men Tell No Tales,2017.0,"[{'cast_id': 1, 'character': 'Captain Jack Spa...","[{'credit_id': '52fe4c9cc3a36847f8236a65', 'de..."
1,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",141052,Justice League,2017.0,"[{'cast_id': 2, 'character': 'Bruce Wayne / Ba...","[{'credit_id': '55ef66dbc3a3686f1700a52d', 'de..."
2,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",284053,Thor: Ragnarok,2017.0,"[{'cast_id': 0, 'character': 'Thor Odinson', '...","[{'credit_id': '56a93fa4c3a36872db001e7a', 'de..."
3,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",283995,Guardians of the Galaxy Vol. 2,2017.0,"[{'cast_id': 3, 'character': 'Peter Quill / St...","[{'credit_id': '59171547925141583c0315a6', 'de..."
4,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na...",245842,The King's Daughter,2017.0,"[{'cast_id': 0, 'character': 'King Louis XIV',...","[{'credit_id': '5431de49c3a36825d300007e', 'de..."

In [23]:
def make_genresList(genre):
    gen = []
    for i in genre:
      if i.get('name') == 'Science Fiction':
        gen.append('Sci-Fi')
      else:
        gen.append(i.get('name'))
    if gen == []:
      return np.NaN
    else:
      return (" ".join(gen))

In [24]:
data['genre_list'] = data['genres'].map(lambda x: make_genresList(x))

In [25]:
data['genre_list']

0      Adventure Action Fantasy Comedy
1      Action Adventure Fantasy Sci-Fi
2      Action Adventure Fantasy Sci-Fi
3       Action Adventure Comedy Sci-Fi
4             Fantasy Action Adventure
                    ...
526                     Romance Comedy
527         Crime Comedy Action Family
528    Family Animation Romance Comedy
529               Crime Drama Thriller
530                                NaN
Name: genre_list, Length: 531, dtype: object

In [26]:
data['cast'][0]

[{'cast_id': 1,
  'character': 'Captain Jack Sparrow',
  'credit_id': '52fe4c9cc3a36847f8236a53',
  'gender': 2,
  'id': 85,
  'name': 'Johnny Depp',
  'order': 0,
  'profile_path': '/kbWValANhZI8rbWZXximXuMN4UN.jpg'},
 {'cast_id': 9,
  'character': 'Captain Armando Salazar',
  'credit_id': '54db4949c3a368122d0017fe',
  'gender': 2,
  'id': 3810,
  'name': 'Javier Bardem',
  'order': 1,
  'profile_path': '/grBOK7Ep09JBE3H5LyV5JaZZ1XZ.jpg'},
 {'cast_id': 16,
  'character': 'Captain Hector Barbossa',
  'credit_id': '54e44e5ec3a368454b00a02f',
  'gender': 2,
  'id': 118,
  'name': 'Geoffrey Rush',
  'order': 2,
  'profile_path': '/5h91WHSK80YtqTk1bMiar2IZzO2.jpg'},
 {'cast_id': 7,
  'character': 'Henry Turner',
  'credit_id': '54db49359251415a0d0012a0',
  'gender': 2,
  'id': 1017347,
  'name': 'Brenton Thwaites',
  'order': 3,
  'profile_path': '/dM0m0OxREfW4HxwV2qQeitS8dfO.jpg'},
 {'cast_id': 8,
  'character': 'Carina Smyth',
  'credit_id': '54db493e925141618f00189a',
  'gender': 1,
  'id': 115150,
  'name': 'Kaya Scodelario',
  'order': 4,
  'profile_path': '/iTrPnn7oS96k0iWPzNxaKCNutB6.jpg'},
 {'cast_id': 14,
  'character': 'Joshamee Gibbs',
  'credit_id': '54e44e31c3a368087b004b56',
  'gender': 2,
  'id': 2449,
  'name': 'Kevin McNally',
  'order': 5,
  'profile_path': '/fIJF3TZn8ckHkcl44oX77GvPv9e.jpg'},
 {'cast_id': 15,
  'character': 'Scrum',
  'credit_id': '54e44e4fc3a3684897002c08',
  'gender': 2,
  'id': 1115,
  'name': 'Stephen Graham',
  'order': 6,
  'profile_path': '/81VZiCA6w8nXG0UjqXCgSJare5N.jpg'},
 {'cast_id': 28,
  'character': 'Scarfield',
  'credit_id': '57f68ea49251413616007300',
  'gender': 2,
  'id': 1371,
  'name': 'David Wenham',
  'order': 7,
  'profile_path': '/xDUXLTF5i2fYx7eSEAR3IdaUb9y.jpg'},
 {'cast_id': 13,
  'character': 'Shansa',
  'credit_id': '54e44e0cc3a3685756009e87',
  'gender': 1,
  'id': 229932,
  'name': 'Golshifteh Farahani',
  'order': 8,
  'profile_path': '/lbsd2lAIQq4egOUXDIfjhte12vv.jpg'},
 {'cast_id': 17,
  'character': 'Will Turner',
  'credit_id': '554768e292514119e00065f8',
  'gender': 2,
  'id': 114,
  'name': 'Orlando Bloom',
  'order': 9,
  'profile_path': '/kKWJlX2tcjqceSfUxnV7Jle5Kt.jpg'},
 {'cast_id': 18,
  'character': 'Marty',
  'credit_id': '554769499251411147001bcb',
  'gender': 2,
  'id': 4030,
  'name': 'Martin Klebba',
  'order': 10,
  'profile_path': '/amlhUrXQ7t1NEPajdj2dQdbC0rt.jpg'},
 {'cast_id': 23,
  'character': 'Mullroy',
  'credit_id': '57e2922bc3a36808b900c1a3',
  'gender': 2,
  'id': 1714,
  'name': 'Angus Barnett',
  'order': 11,
  'profile_path': '/usYsWRccdM4Y00RycsQFFOdNVe.jpg'},
 {'cast_id': 19,
  'character': 'Cremble',
  'credit_id': '55476961c3a3680ce80091da',
  'gender': 0,
  'id': 1193833,
  'name': 'Adam Brown',
  'order': 12,
  'profile_path': '/54iHvIA8ZTNfvKpb2ZxRY73A5MZ.jpg'},
 {'cast_id': 38,
  'character': 'Bollard',
  'credit_id': '57f68ea7925141360100754f',
  'gender': 0,
  'id': 1355191,
  'name': 'Danny Kirrane',
  'order': 13,
  'profile_path': '/vn4NIHMJb0Sf39MOP3cgMdk2N8h.jpg'},
 {'cast_id': 22,
  'character': 'Murtogg',
  'credit_id': '57e29210c3a3680a110056ca',
  'gender': 0,
  'id': 1713,
  'name': 'Giles New',
  'order': 14,
  'profile_path': '/e0Ap9fkLAFcxLVHpK8KH2TQV3wI.jpg'},
 {'cast_id': 84,
  'character': 'Pike',
  'credit_id': '591f7a46c3a368723d03b63b',
  'gender': 0,
  'id': 1819920,
  'name': 'Delroy Atkinson',
  'order': 15,
  'profile_path': '/XcMnuXUPLNYzRL58s5TKPUFq2g.jpg'},
 {'cast_id': 21,
  'character': 'Uncle Jack',
  'credit_id': '57e291cf92514118f700625d',
  'gender': 2,
  'id': 10215,
  'name': 'Paul McCartney',
  'order': 16,
  'profile_path': '/v7FagbD9EY4MVUtcrk9ESjPWV7q.jpg'},
 {'cast_id': 43,
  'character': 'Elizabeth Swann',
  'credit_id': '58f708cf9251415dec00953a',
  'gender': 1,
  'id': 116,
  'name': 'Keira Knightley',
  'order': 17,
  'profile_path': '/rv6quYbTgFTmBAoePwy5xuurW3g.jpg'},
 {'cast_id': 91,
  'character': 'Young Jack Sparrow',
  'credit_id': '59338b3dc3a3685a35016ca6',
  'gender': 0,
  'id': 1772106,
  'name': 'Anthony De La Torre',
  'order': 18,
  'profile_path': '/sgtspl6fcAuhPo4wKYkzlzSgvmg.jpg'},
 {'cast_id': 92,
  'character': 'Young Henry Turner',
  'credit_id': '59338b66c3a36859de01633a',
  'gender': 2,
  'id': 1828139,
  'name': 'Lewis McGowan',
  'order': 19,
  'profile_path': '/27pyhArCRR8ZqIyiak9c0N0l1nz.jpg'},
 {'cast_id': 85,
  'character': 'Lieutenant Lesaro',
  'credit_id': '591f7a8cc3a368799b037a0a',
  'gender': 2,
  'id': 1089049,
  'name': 'Juan Carlos Vellido',
  'order': 20,
  'profile_path': '/m1GEfFgcDNPTCTGUhrita7d5ec1.jpg'},
 {'cast_id': 86,
  'character': 'Officer Madga',
  'credit_id': '591f7acc925141482f039128',
  'gender': 0,
  'id': 1530814,
  'name': 'Rodney Afif',
  'order': 21,
  'profile_path': '/wr1gTOcRcyKO4fYlUwsPLRlP7bn.jpg'},
 {'cast_id': 87,
  'character': 'Mayor Dix',
  'credit_id': '591f7ae1c3a3687a64039857',
  'gender': 2,
  'id': 27752,
  'name': 'Bruce Spence',
  'order': 22,
  'profile_path': '/pwJJBmO9MG3OxVX9efGrB6BTFyw.jpg'},
 {'cast_id': 31,
  'character': "Mayor's Wife",
  'credit_id': '57f68ea5c3a3681607006e8c',
  'gender': 1,
  'id': 61914,
  'name': 'Zoe Ventoura',
  'order': 23,
  'profile_path': '/fMBiXCtCTqpEmjAfTVC3NssVMCk.jpg'},
 {'cast_id': 33,
  'character': 'Maddox',
  'credit_id': '57f68ea6c3a3681607006e8e',
  'gender': 2,
  'id': 1112872,
  'name': 'James Mackay',
  'order': 24,
  'profile_path': '/nJPYaP94wXwh1bYnFzkQh1BB30l.jpg'},
 {'cast_id': 51,
  'character': 'Upper Class Lady',
  'credit_id': '591293c59251414edb04e228',
  'gender': 1,
  'id': 1813772,
  'name': 'Brooke Chamberlain',
  'order': 25,
  'profile_path': '/vYqTEUUY4EG6jPzP5wnZNhy4aAy.jpg'},
 {'cast_id': 45,
  'character': 'Young Captain Teague',
  'credit_id': '5912926dc3a368646b0521a2',
  'gender': 2,
  'id': 16811,
  'name': 'Alexander Scheer',
  'order': 26,
  'profile_path': '/f6eWj5VEMBb3O3aviqgMoujM3kf.jpg'},
 {'cast_id': 32,
  'character': 'Pirate Broom',
  'credit_id': '57f68ea5925141360d007429',
  'gender': 0,
  'id': 61784,
  'name': 'Goran D. Kleut',
  'order': 27,
  'profile_path': '/ikAVxzlgo4bXQWn4GpoFfDrgnth.jpg'},
 {'cast_id': 40,
  'character': 'Pirate',
  'credit_id': '57f68ea892514136130074b0',
  'gender': 0,
  'id': 1535048,
  'name': 'Wassim Hawat',
  'order': 28,
  'profile_path': '/yTJCBoDa1OKt7h6JDKYaZnlLqeA.jpg'},
 {'cast_id': 37,
  'character': 'British Executioner',
  'credit_id': '57f68ea7925141360100754d',
  'gender': 0,
  'id': 1394235,
  'name': "Ben O'Toole",
  'order': 29,
  'profile_path': '/f9cCCp1PlRZo4sWdwppHTeOC8kZ.jpg'},
 {'cast_id': 42,
  'character': 'Young Pirate Jeff',
  'credit_id': '57f68ea8c3a368161c007391',
  'gender': 2,
  'id': 1690240,
  'name': 'Finn Ireland',
  'order': 30,
  'profile_path': '/x1IZJZLFHboPhZbdycZcNo2kZoM.jpg'},
 {'cast_id': 44,
  'character': 'Spanish Officer',
  'credit_id': '59129248c3a36864ec048639',
  'gender': 0,
  'id': 1414764,
  'name': 'Nico Cortez',
  'order': 31,
  'profile_path': '/ujk9vAlutbLUe9VbjPE6RDuQqVC.jpg'},
 {'cast_id': 49,
  'character': 'Young Greenhorn',
  'credit_id': '591293549251414eca04accf',
  'gender': 0,
  'id': 1394227,
  'name': 'James Fraser',
  'order': 32,
  'profile_path': '/4lcpUIRwFVmPkkxUvYdUNSQQddc.jpg'},
 {'cast_id': 115,
  'character': 'Woman',
  'credit_id': '59c783a3c3a368140305a3f1',
  'gender': 0,
  'id': 1499792,
  'name': 'Derani Scarr',
  'order': 33,
  'profile_path': '/aob0mfWTaJaUlHDVef2dA7Dlwhc.jpg'},
 {'cast_id': 93,
  'character': 'Grimes',
  'credit_id': '5999d18a9251414a18001dd4',
  'gender': 0,
  'id': 126200,
  'name': 'Robert Morgan',
  'order': 34,
  'profile_path': '/8sFiiilQmp2jvLKn6h5QPchA5Gq.jpg'},
 {'cast_id': 94,
  'character': 'Pirate with Broom',
  'credit_id': '59a67afe9251411293009e0c',
  'gender': 0,
  'id': 61784,
  'name': 'Goran D. Kleut',
  'order': 35,
  'profile_path': '/ikAVxzlgo4bXQWn4GpoFfDrgnth.jpg'},
 {'cast_id': 29,
  'character': 'Spanish Soldier',
  'credit_id': '57f68ea5925141360100754a',
  'gender': 2,
  'id': 1386458,
  'name': 'Mahesh Jadu',
  'order': 36,
  'profile_path': '/gfcZiYji4x3tjGQq7vTK8goz40D.jpg'},
 {'cast_id': 34,
  'character': 'British Soldier',
  'credit_id': '57f68ea692514136130074ae',
  'gender': 0,
  'id': 1394427,
  'name': 'Travis Jeffery',
  'order': 37,
  'profile_path': '/lOR40uoh60aKx3ORArhKBQAaBO6.jpg'},
 {'cast_id': 111,
  'character': 'British Soldier',
  'credit_id': '59c77df0c3a36813ed057ad8',
  'gender': 0,
  'id': 1205492,
  'name': 'Akos Armont',
  'order': 38,
  'profile_path': '/t0nRw07H8aXtzz7az5yjDSZwVVg.jpg'},
 {'cast_id': 104,
  'character': 'British Soldier',
  'credit_id': '59c6c742c3a368141e044fa3',
  'gender': 0,
  'id': 1533328,
  'name': 'Sean Lynch',
  'order': 39,
  'profile_path': '/m8Q9SaYTWJ5iXLoS2E4zvcD4tQ1.jpg'},
 {'cast_id': 95,
  'character': 'British Soldier',
  'credit_id': '59a67b84c3a36827990085f8',
  'gender': 0,
  'id': 1394235,
  'name': "Ben O'Toole",
  'order': 40,
  'profile_path': '/f9cCCp1PlRZo4sWdwppHTeOC8kZ.jpg'},
 {'cast_id': 105,
  'character': 'CG Ghost Soldier',
  'credit_id': '59c6c7d69251415b32049e77',
  'gender': 0,
  'id': 1893668,
  'name': 'Akshay Caplash',
  'order': 41,
  'profile_path': '/s3QTX4IdN3wUNN9YiZBid2ANhmM.jpg'},
 {'cast_id': 106,
  'character': 'CG Ghost Soldier',
  'credit_id': '59c6c8629251415b6e047778',
  'gender': 2,
  'id': 1893671,
  'name': 'Rafael Torrijos',
  'order': 42,
  'profile_path': '/lro1QSBv5cmkiO8R8RbxADGXIka.jpg'},
 {'cast_id': 112,
  'character': 'CG Ghost Soldier',
  'credit_id': '59c7805d9251415b87053e7f',
  'gender': 0,
  'id': 1893872,
  'name': 'Mivon Prince-Leyva',
  'order': 43,
  'profile_path': '/c5CfJBn3B0Ce07TxgPUx9ttUTLv.jpg'},
 {'cast_id': 110,
  'character': 'First Officer Wade',
  'credit_id': '59c77d9cc3a3681454052a75',
  'gender': 2,
  'id': 76068,
  'name': 'Michael Dorman',
  'order': 44,
  'profile_path': '/95hvX99zyHIpHJ9Ajv35TWgNlGN.jpg'},
 {'cast_id': 116,
  'character': 'Officer Cole',
  'credit_id': '59c784a99251415b870541ed',
  'gender': 2,
  'id': 33184,
  'name': 'Rohan Nichol',
  'order': 45,
  'profile_path': '/nzvL3MRpADYWlH4ppyYgmCnM1kZ.jpg'},
 {'cast_id': 96,
  'character': 'Officer Santos',
  'credit_id': '59c6b999c3a368144304be34',
  'gender': 0,
  'id': 1893640,
  'name': 'Rupert Raineri',
  'order': 46,
  'profile_path': '/oXeONe2M6qwiVlDFpJIT1wrA9Ek.jpg'},
 {'cast_id': 97,
  'character': 'Officer Moss',
  'credit_id': '59c6b9fec3a368143004b954',
  'gender': 0,
  'id': 1893641,
  'name': 'Stephen Lopez',
  'order': 47,
  'profile_path': '/hYoItjKNWnncBbjM3voLEu5DnN8.jpg'},
 {'cast_id': 109,
  'character': 'Captain Toms',
  'credit_id': '59c77d659251415b5d05482d',
  'gender': 0,
  'id': 75744,
  'name': 'Richard Piper',
  'order': 48,
  'profile_path': '/3SEI2j8jIzVthrYifpMgjNC4MHp.jpg'},
 {'cast_id': 98,
  'character': 'Mr. Krill',
  'credit_id': '59c6bc1dc3a368140304c936',
  'gender': 0,
  'id': 1347909,
  'name': 'Justin Smith',
  'order': 49,
  'profile_path': '/7knG8VrDuEmhAZT2B4p1zmMjDJy.jpg'},
 {'cast_id': 99,
  'character': 'Mr. Swift',
  'credit_id': '59c6be5f9251415b2804b325',
  'gender': 0,
  'id': 1486057,
  'name': 'John Leary',
  'order': 50,
  'profile_path': '/bCP5mcXgFp5X7mq7jTmYpmBbtHE.jpg'},
 {'cast_id': 100,
  'character': 'Bowen',
  'credit_id': '59c6c070c3a368141e0448fa',
  'gender': 0,
  'id': 1014587,
  'name': 'Bryan Probets',
  'order': 51,
  'profile_path': '/wp0o01OuR5YF3DWjBBUYAWUbzHA.jpg'},
 {'cast_id': 113,
  'character': 'Pig Kelly',
  'credit_id': '59c7810a9251415b240582b0',
  'gender': 2,
  'id': 57904,
  'name': 'Ken Radley',
  'order': 52,
  'profile_path': '/jqiM2DbXtNRF3yxRaU2nkYzewEJ.jpg'},
 {'cast_id': 101,
  'character': 'Beatrice',
  'credit_id': '59c6c14bc3a36813ed04aed4',
  'gender': 1,
  'id': 1252521,
  'name': 'Hannah Walters',
  'order': 53,
  'profile_path': '/3hUokXHcRhdpM971cb3kbaVSrY8.jpg'},
 {'cast_id': 114,
  'character': 'Priest',
  'credit_id': '59c7826c9251415b32055db4',
  'gender': 0,
  'id': 1545346,
  'name': 'Jonathan Elsom',
  'order': 54,
  'profile_path': '/i1LEAdB5y6zg4lVa01hV9ZZo7Ew.jpg'},
 {'cast_id': 102,
  'character': 'Captain Morgan',
  'credit_id': '59c6c217c3a3681454046e90',
  'gender': 2,
  'id': 143328,
  'name': 'K. Todd Freeman',
  'order': 55,
  'profile_path': '/2L7Qh4hA2dsCIPZAVfgerax7i2q.jpg'},
 {'cast_id': 107,
  'character': 'Jail Guard',
  'credit_id': '59c6c957c3a368140304d946',
  'gender': 0,
  'id': 1893677,
  'name': 'James Lawson',
  'order': 56,
  'profile_path': '/gtcdsTruLPzpL2xJhePsOq38LjX.jpg'},
 {'cast_id': 108,
  'character': "Uncle Jack's Cellmate",
  'credit_id': '59c6ca34c3a3681461041481',
  'gender': 0,
  'id': 1216570,
  'name': 'Darcy Laurie',
  'order': 57,
  'profile_path': '/bTZgOB4wl4ECbHiGjoKQAQdvTUW.jpg'},
 {'cast_id': 30,
  'character': 'Townswoman (uncredited)',
  'credit_id': '57f68ea592514172c5002e01',
  'gender': 1,
  'id': 1255055,
  'name': 'Jessica Green',
  'order': 58,
  'profile_path': '/7l3bkNv92uii8im5B4vyF0ABgcS.jpg'},
 {'cast_id': 52,
  'character': 'Townswoman (uncredited)',
  'credit_id': '591294019251414e8504da81',
  'gender': 0,
  'id': 1345090,
  'name': 'Haley Madison',
  'order': 59,
  'profile_path': '/3XJGp5oJCGvqosOhSSgQZWI8cKo.jpg'},
 {'cast_id': 36,
  'character': 'Townschild (uncredited)',
  'credit_id': '57f68ea7c3a36816250071ea',
  'gender': 0,
  'id': 1632129,
  'name': 'Kiara Freeman',
  'order': 60,
  'profile_path': '/3n5EDxHBritMzqxIS47A6Qccg74.jpg'},
 {'cast_id': 35,
  'character': 'Townschild (uncredited)',
  'credit_id': '57f68ea6c3a3681604007202',
  'gender': 0,
  'id': 1690237,
  'name': 'Piper Nairn',
  'order': 61,
  'profile_path': '/cOVpgx5JF9XeFUF2am9Bk4f5wkh.jpg'},
 {'cast_id': 53,
  'character': 'Townsperson (uncredited)',
  'credit_id': '5912942ec3a36864c604d3d7',
  'gender': 1,
  'id': 1692989,
  'name': 'Suzanne Dervish-Ali',
  'order': 62,
  'profile_path': '/7OQgHuuzFbtO9jAF4w6zcuzqmAK.jpg'},
 {'cast_id': 50,
  'character': 'Townsperson (uncredited)',
  'credit_id': '591293a5c3a368650a04aff2',
  'gender': 0,
  'id': 1813771,
  'name': 'Donnie Baxter',
  'order': 63,
  'profile_path': '/dm2cSQwySnOj9sWqca9nBspS8sL.jpg'},
 {'cast_id': 41,
  'character': 'Maid (uncredited)',
  'credit_id': '57f68ea8925141360300747b',
  'gender': 0,
  'id': 1690239,
  'name': 'Winnie Mzembe',
  'order': 64,
  'profile_path': '/lUTozzeBvTZZkpUQLE5V5baS12X.jpg'},
 {'cast_id': 39,
  'character': 'Greenwich Village Upper Class Lady (uncredited)',
  'credit_id': '57f68ea892514172c5002e04',
  'gender': 0,
  'id': 1690238,
  'name': 'Christie-Lee Britten',
  'order': 65,
  'profile_path': '/uNSjA73XjDbQMJB1XGnoKB89zux.jpg'},
 {'cast_id': 48,
  'character': 'Twin Middle Class Lady (uncredited)',
  'credit_id': '5912932f9251414e8904ee64',
  'gender': 0,
  'id': 1813770,
  'name': 'Mollie McGregor',
  'order': 66,
  'profile_path': '/q4XZ9rV1TbrsqvK91a9FAMudL6C.jpg'},
 {'cast_id': 103,
  'character': 'Twin Middle Class Lady (uncredited)',
  'credit_id': '59c6c5399251415b6e0473ea',
  'gender': 0,
  'id': 1571654,
  'name': 'Sophia McGregor',
  'order': 67,
  'profile_path': '/egbKVmd3f1xgAq90vDiRLLZIFXx.jpg'}]

In [38]:
def get_actor1(x):
    casts = []
    for i in x:
      casts.append(i.get('name'))
    if casts == []:
      return np.NaN
    else:
      return (casts[0])

In [39]:
data['actor_1_name'] = data['cast'].map(lambda x: get_actor1(x))

In [40]:
data.head()

,genres,id,title,year,cast,crew,genre_list,actor_1_name,actor_2_name,actor_3_name
0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",166426,Pirates of the Caribbean: Dead Men Tell No Tales,2017.0,"[{'cast_id': 1, 'character': 'Captain Jack Spa...","[{'credit_id': '52fe4c9cc3a36847f8236a65', 'de...",Adventure Action Fantasy Comedy,Johnny Depp,Javier Bardem,Geoffrey Rush
1,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",141052,Justice League,2017.0,"[{'cast_id': 2, 'character': 'Bruce Wayne / Ba...","[{'credit_id': '55ef66dbc3a3686f1700a52d', 'de...",Action Adventure Fantasy Sci-Fi,Ben Affleck,Henry Cavill,Gal Gadot
2,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",284053,Thor: Ragnarok,2017.0,"[{'cast_id': 0, 'character': 'Thor Odinson', '...","[{'credit_id': '56a93fa4c3a36872db001e7a', 'de...",Action Adventure Fantasy Sci-Fi,Chris Hemsworth,Tom Hiddleston,Cate Blanchett
3,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",283995,Guardians of the Galaxy Vol. 2,2017.0,"[{'cast_id': 3, 'character': 'Peter Quill / St...","[{'credit_id': '59171547925141583c0315a6', 'de...",Action Adventure Comedy Sci-Fi,Chris Pratt,Zoe Saldana,Dave Bautista
4,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na...",245842,The King's Daughter,2017.0,"[{'cast_id': 0, 'character': 'King Louis XIV',...","[{'credit_id': '5431de49c3a36825d300007e', 'de...",Fantasy Action Adventure,Pierce Brosnan,William Hurt,Benjamin Walker

In [41]:
#Actor 2
def get_actor2(x):
    casts = []
    for i in x:
      casts.append(i.get('name'))
    if casts == [] or len(casts) <= 1:
      return np.NaN
    else:
      return (casts[1])

data['actor_2_name'] = data['cast'].map(lambda x: get_actor2(x))

In [33]:
#Actor 3

def get_actor3(x):
    casts = []
    for i in x:
      casts.append(i.get('name'))
    if casts == [] or len(casts) <= 2:
      return np.NaN
    else:
      return (casts[2])

data['actor_3_name'] = data['cast'].map(lambda x: get_actor3(x))

In [34]:
data.head()

,genres,id,title,year,cast,crew,genre_list,actor_1_name,actor_2_name,actor_3_name
0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",166426,Pirates of the Caribbean: Dead Men Tell No Tales,2017.0,"[{'cast_id': 1, 'character': 'Captain Jack Spa...","[{'credit_id': '52fe4c9cc3a36847f8236a65', 'de...",Adventure Action Fantasy Comedy,Johnny Depp,Javier Bardem,Geoffrey Rush
1,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",141052,Justice League,2017.0,"[{'cast_id': 2, 'character': 'Bruce Wayne / Ba...","[{'credit_id': '55ef66dbc3a3686f1700a52d', 'de...",Action Adventure Fantasy Sci-Fi,Ben Affleck,Henry Cavill,Gal Gadot
2,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",284053,Thor: Ragnarok,2017.0,"[{'cast_id': 0, 'character': 'Thor Odinson', '...","[{'credit_id': '56a93fa4c3a36872db001e7a', 'de...",Action Adventure Fantasy Sci-Fi,Chris Hemsworth,Tom Hiddleston,Cate Blanchett
3,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",283995,Guardians of the Galaxy Vol. 2,2017.0,"[{'cast_id': 3, 'character': 'Peter Quill / St...","[{'credit_id': '59171547925141583c0315a6', 'de...",Action Adventure Comedy Sci-Fi,Chris Pratt,Zoe Saldana,Dave Bautista
4,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na...",245842,The King's Daughter,2017.0,"[{'cast_id': 0, 'character': 'King Louis XIV',...","[{'credit_id': '5431de49c3a36825d300007e', 'de...",Fantasy Action Adventure,Pierce Brosnan,William Hurt,Benjamin Walker

### Directors

In [42]:
def get_directors(x):
    dt = []
    for i in x:
      if i.get('job') == 'Director':
        dt.append(i.get('name'))
    if dt == []:
      return np.NaN
    else:
      return (" ".join(dt))

In [45]:
data['director_name'] = data['crew'].map(lambda x: get_directors(x))

In [47]:
data = data.drop('director_names', axis=1)
data.head()

,genres,id,title,year,cast,crew,genre_list,actor_1_name,actor_2_name,actor_3_name,director_name
0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",166426,Pirates of the Caribbean: Dead Men Tell No Tales,2017.0,"[{'cast_id': 1, 'character': 'Captain Jack Spa...","[{'credit_id': '52fe4c9cc3a36847f8236a65', 'de...",Adventure Action Fantasy Comedy,Johnny Depp,Javier Bardem,Geoffrey Rush,Joachim Rønning Espen Sandberg
1,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",141052,Justice League,2017.0,"[{'cast_id': 2, 'character': 'Bruce Wayne / Ba...","[{'credit_id': '55ef66dbc3a3686f1700a52d', 'de...",Action Adventure Fantasy Sci-Fi,Ben Affleck,Henry Cavill,Gal Gadot,Zack Snyder
2,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",284053,Thor: Ragnarok,2017.0,"[{'cast_id': 0, 'character': 'Thor Odinson', '...","[{'credit_id': '56a93fa4c3a36872db001e7a', 'de...",Action Adventure Fantasy Sci-Fi,Chris Hemsworth,Tom Hiddleston,Cate Blanchett,Taika Waititi
3,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",283995,Guardians of the Galaxy Vol. 2,2017.0,"[{'cast_id': 3, 'character': 'Peter Quill / St...","[{'credit_id': '59171547925141583c0315a6', 'de...",Action Adventure Comedy Sci-Fi,Chris Pratt,Zoe Saldana,Dave Bautista,James Gunn
4,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na...",245842,The King's Daughter,2017.0,"[{'cast_id': 0, 'character': 'King Louis XIV',...","[{'credit_id': '5431de49c3a36825d300007e', 'de...",Fantasy Action Adventure,Pierce Brosnan,William Hurt,Benjamin Walker,Sean McNamara

In [48]:
#feature selection
movie_data = data.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genre_list','title']]

In [49]:
movie_data.head()

,director_name,actor_1_name,actor_2_name,actor_3_name,genre_list,title
0,Joachim Rønning Espen Sandberg,Johnny Depp,Javier Bardem,Geoffrey Rush,Adventure Action Fantasy Comedy,Pirates of the Caribbean: Dead Men Tell No Tales
1,Zack Snyder,Ben Affleck,Henry Cavill,Gal Gadot,Action Adventure Fantasy Sci-Fi,Justice League
2,Taika Waititi,Chris Hemsworth,Tom Hiddleston,Cate Blanchett,Action Adventure Fantasy Sci-Fi,Thor: Ragnarok
3,James Gunn,Chris Pratt,Zoe Saldana,Dave Bautista,Action Adventure Comedy Sci-Fi,Guardians of the Galaxy Vol. 2
4,Sean McNamara,Pierce Brosnan,William Hurt,Benjamin Walker,Fantasy Action Adventure,The King's Daughter

In [50]:
movie_data.isna().sum()

director_name     4
actor_1_name     22
actor_2_name     55
actor_3_name     70
genre_list        7
title             0
dtype: int64

In [51]:
movie_data = movie_data.dropna(how='any')

In [52]:
movie_data.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genre_list       0
title            0
dtype: int64

In [53]:
movie_data = movie_data.rename(columns={'genre_list':'genres'})
movie_data = movie_data.rename(columns={'title':'movie_title'})

In [54]:
#converting all movie titles to lowercase
movie_data['movie_title'] = movie_data['movie_title'].str.lower()

In [55]:
 movie_data['col_merge'] = movie_data['actor_1_name'] + ' ' + movie_data['actor_2_name'] + ' ' + movie_data['actor_3_name'] + ' ' + movie_data['director_name'] + ' ' + movie_data['genres']

In [58]:
movie_data.col_merge[0]

'Johnny Depp Javier Bardem Geoffrey Rush Joachim Rønning Espen Sandberg Adventure Action Fantasy Comedy'

In [59]:
old_data = pd.read_csv('/content/data1.csv')

In [60]:
old_data['col_merge'] = old_data['actor_1_name'] + ' ' + old_data['actor_2_name'] + ' ' + old_data['actor_3_name'] + ' ' + old_data['director_name'] + ' ' + old_data['genres']

In [63]:
new_data = pd.concat([old_data, movie_data], ignore_index=True)

In [64]:
new_data

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,col_merge
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,Unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker Unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
5496,Jim Strouse,Jessica Williams,Chris O'Dowd,Keith Stanfield,Romance Comedy,the incredible jessica james,Jessica Williams Chris O'Dowd Keith Stanfield ...
5497,Farhad Mann,Adelaide Kane,Benjamin Hollingsworth,Jean Louisa Kelly,Romance,can't buy my love,Adelaide Kane Benjamin Hollingsworth Jean Loui...
5498,Hannaleena Hauru,Inka Haapamäki,Rosa Honkonen,Tiitus Rantala,Romance Comedy,thick lashes of lauri mäntyvaara,Inka Haapamäki Rosa Honkonen Tiitus Rantala Ha...
5499,Jonathan A. Rosenbaum,Lou Diamond Phillips,Wallace Shawn,Gina Holden,Crime Comedy Action Family,cop and a half: new recruit,Lou Diamond Phillips Wallace Shawn Gina Holden...
5500,Ravi Udyawar,Sridevi Kapoor,Sajal Ali,Akshaye Khanna,Crime Drama Thriller,mom,Sridevi Kapoor Sajal Ali Akshaye Khanna Ravi U...

In [65]:
new_data.drop_duplicates(subset='movie_title', keep='last', inplace=True)

In [66]:
new_data.to_csv('new_data.csv', index=False)